### ISSUE TITLE
Something went wrong in latexdiff. Deleting diff.tex and abort

### ISSUE THREAD

**Issue by BEpresent** [ftilmann/latexdiff#55] opened 2016-09-06 13:54 UTC
example:

this may be test2.tex

```
%\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{article}

\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{revtex4-1}

%\documentclass[aps,pre,amsmath,amssymb,lengthcheck,showpacs,floatfix]{revtex4-1}
%\documentclass[superscriptaddress,twocolumn,pre,amsmath,showpacs,bibliography]{revtex4-1}
\usepackage{siunitx}
\usepackage[]{inputenc}
\usepackage{graphicx}% Include figure files
\usepackage{dcolumn}% Align table columns on decimal point
\usepackage{bm}% bold math
\usepackage{colordvi}
\usepackage{epsfig}
%\usepackage{bm}
\usepackage{subcaption}
\usepackage{commath}
\usepackage[usenames]{color}
%\usepackage{natbib}
\usepackage{url}
 \usepackage[english]{babel}





\begin{document}

\title{Draft 2016}

\author{xxxxxx}
%\affiliation{dadasdad}


\begin{abstract}
\noindent  Abstract: Draft-version Paper.Test
\end{abstract}

\date{\today}
%\pacs{???}






\maketitle

\maketitle
%\onecolumngrid
\section{Introduction}




asdad aLorem ipsum dolor sit amet, conseteted diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\section{Theory (WIP)}
%\bibliographystyle{unsrt}

%\bibliographystyle{abbrv}

\bibliographystyle{unsrtnat}

\bibliography{ExportedItems}


\end{document}
```

This is test1.tex

```
%\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{article}

\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{revtex4-1}

%\documentclass[aps,pre,amsmath,amssymb,lengthcheck,showpacs,floatfix]{revtex4-1}
%\documentclass[superscriptaddress,twocolumn,pre,amsmath,showpacs,bibliography]{revtex4-1}
\usepackage{siunitx}
\usepackage[]{inputenc}
\usepackage{graphicx}% Include figure files
\usepackage{dcolumn}% Align table columns on decimal point
\usepackage{bm}% bold math
\usepackage{colordvi}
\usepackage{epsfig}
%\usepackage{bm}
\usepackage{subcaption}
\usepackage{commath}
\usepackage[usenames]{color}
%\usepackage{natbib}
\usepackage{url}
 \usepackage[english]{babel}





\begin{document}

\title{Draft 2016}

\author{xxxxxx}
%\affiliation{dadasdad}


\begin{abstract}
\noindent  Abstract: Draft-version Paper.Test
\end{abstract}

\date{\today}
%\pacs{???}






\maketitle

\maketitle
%\onecolumngrid
\section{Introduction}




Lorem ipsum dolor sit amet, conseteted diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\section{Theory (WIP)}
%\bibliographystyle{unsrt}

%\bibliographystyle{abbrv}

\bibliographystyle{unsrtnat}

\bibliography{ExportedItems}


\end{document}
```

Now using `latexdiff-vc test1.tex test2.tex > diff.tex ` 

results in 

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{ <-- HERE DIFchgb(\d*)}{.*\\abspage{(\d*)}}/ at /usr/bin/latexdiff-vc line 451.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{DIFchgb(\d*)}{ <-- HERE .*\\abspage{(\d*)}}/ at /usr/bin/latexdiff-vc line 451.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{DIFchgb(\d*)}{.*\\abspage{ <-- HERE (\d*)}}/ at /usr/bin/latexdiff-vc line 451.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{ <-- HERE DIFchge(\d*)}{.*\\abspage{(\d*)}}/ at /usr/bin/latexdiff-vc line 454.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{DIFchge(\d*)}{ <-- HERE .*\\abspage{(\d*)}}/ at /usr/bin/latexdiff-vc line 454.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{DIFchge(\d*)}{.*\\abspage{ <-- HERE (\d*)}}/ at /usr/bin/latexdiff-vc line 454.
Working on  test2.tex 
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\includeonly{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1468.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(^(?:[^%\n]|\\%)*)\\bibliography{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1503.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(^(?:[^%\n]|\\%)*)\\subfile{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1518.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(?<!\\)\\{ <-- HERE / at /usr/bin/latexdiff line 2247.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE MATHMODE}((?:(.(?!(?<!\\)\&|\\\\))*)?)\\end{MATHMODE}/ at /usr/bin/latexdiff line 2572.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{MATHMODE}((?:(.(?!(?<!\\)\&|\\\\))*)?)\\end{ <-- HERE MATHMODE}/ at /usr/bin/latexdiff line 2572.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE MATHMODE}(.*?)\\end{MATHMODE}/ at /usr/bin/latexdiff line 2574.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{MATHMODE}(.*?)\\end{ <-- HERE MATHMODE}/ at /usr/bin/latexdiff line 2574.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE SQUAREBRACKET}/ at /usr/bin/latexdiff line 2655.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE SQUAREBRACKET}/ at /usr/bin/latexdiff line 2656.
Unknown encoding '' at /usr/bin/latexdiff line 1341.
Something went wrong in latexdiff. Deleting test2-diff.tex and abort

```

**Comment by ftilmann** [comment] 2016-09-06 14:05
The deprecation warnings have been fixed in the latest release (1.2.0). 

 Have you tried running this through latexdiff directly (not through latexdiff-vc), and do you also get the unknown encoding warning then?

In order to be able to look into this I would have to know the exact version and flavour of latexdiff, i.e. post output of `latexdiff --version` and a link where I can download the test files as binaries. Normally posting as you have done is the right thing to do, but it looks like some encoding related issue, and I don't think that's  preserved on multiple copy/pasting

**Comment by BEpresent** [comment] 2016-09-06 14:14
latexdiff --version   gives 

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\includeonly{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1468.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(^(?:[^%\n]|\\%)*)\\bibliography{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1503.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(^(?:[^%\n]|\\%)*)\\subfile{ <-- HERE (.*?)}/ at /usr/bin/latexdiff line 1518.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(?<!\\)\\{ <-- HERE / at /usr/bin/latexdiff line 2247.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE MATHMODE}((?:(.(?!(?<!\\)\&|\\\\))*)?)\\end{MATHMODE}/ at /usr/bin/latexdiff line 2572.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{MATHMODE}((?:(.(?!(?<!\\)\&|\\\\))*)?)\\end{ <-- HERE MATHMODE}/ at /usr/bin/latexdiff line 2572.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE MATHMODE}(.*?)\\end{MATHMODE}/ at /usr/bin/latexdiff line 2574.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{MATHMODE}(.*?)\\end{ <-- HERE MATHMODE}/ at /usr/bin/latexdiff line 2574.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE SQUAREBRACKET}/ at /usr/bin/latexdiff line 2655.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin{ <-- HERE SQUAREBRACKET}/ at /usr/bin/latexdiff line 2656.
This is LATEXDIFF 1.1.1  (Algorithm::Diff 1.15 so, Perl v5.24.0)
  (c) 2004-2015 F J Tilmann

```

Which is not the most recent version indeed. What I actually did is to git clone your repository from here. And to execute latexdiff-vc locally from within the directory (just using latexdiff this way reults in the same error.)

**Comment by ftilmann** [comment] 2016-09-06 14:35
OK, actually I know what the problem is from looking at your example. The troublesome line is

`\usepackage[]{inputenc}`

I am not sure what this is doing because normally in the square brackets you would put the encoding of your file. Check by commenting out in both old and new file, if this line is really needed. If for some reason you cannot remove it you can override the guessing of the encoding by using `--encoding` option ( you must specify then the real encoding of your file, possibly simply `ascii`; see manual pages for valid choices)

**Closed by ftilmann** 2016-09-06 14:35 UTC

**Comment by BEpresent** [comment] 2016-09-06 14:54
Thanks,  `\usepackage[]{inputenc} `was indeed the problem.

Do you know when/if this new release will be integrated into texlive ? Otherwise I will try out the stand-alone version for now.
