### ISSUE TITLE
invisible non-ASCII character error in Windows

### ISSUE THREAD

**Issue by garretchristensen** [ftilmann/latexdiff#46] opened 2016-02-04 02:25 UTC
Using Windows 7, latexdiff 1.0.4, and MikTex 2.9, I get an error every time I try to compile a latexdiff-created tex file. Everything _looks_ like it should work, but it doesn't compile. Unless I copy and paste the exact same text, or even delete and then ctrl+Z undo the deletion. Then it works.

For example, if I start with old.tex:

```
\documentclass{article}
\begin{document}
This is the old text.
\end{document}
```

and new.tex:
```
    \documentclass{article}
    \begin{document}
    This is the NEW text.
    \end{document}
```

and then use the command line to run:
    latexdiff old.tex new.tex > diff.tex

then diff.tex appears as follows:
```
\documentclass{article}
%DIF LATEXDIFF DIFFERENCE FILE
%DIF DEL old.tex   Wed Feb  3 18:08:06 2016
%DIF ADD new.tex   Wed Feb  3 18:08:27 2016
%DIF PREAMBLE EXTENSION ADDED BY LATEXDIFF
%DIF UNDERLINE PREAMBLE %DIF PREAMBLE
\RequirePackage[normalem]{ulem} %DIF PREAMBLE
\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE
\providecommand{\DIFadd}[1]{{\protect\color{blue}\uwave{#1}}} %DIF PREAMBLE
\providecommand{\DIFdel}[1]{{\protect\color{red}\sout{#1}}}                      %DIF PREAMBLE
%DIF SAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddbegin}{} %DIF PREAMBLE
\providecommand{\DIFaddend}{} %DIF PREAMBLE
\providecommand{\DIFdelbegin}{} %DIF PREAMBLE
\providecommand{\DIFdelend}{} %DIF PREAMBLE
%DIF FLOATSAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}} %DIF PREAMBLE
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}} %DIF PREAMBLE
\providecommand{\DIFaddbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFaddendFL}{} %DIF PREAMBLE
\providecommand{\DIFdelbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFdelendFL}{} %DIF PREAMBLE
%DIF END PREAMBLE EXTENSION ADDED BY LATEXDIFF

\begin{document}
This is the \DIFdelbegin \DIFdel{old }\DIFdelend \DIFaddbegin \DIFadd{NEW }\DIFaddend text.
\end{document}
```

Which totally looks like it's fine. But it's not. I get the following when I try and compile via the command line, pdflatex diff.tex, I get:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
entering extended mode (diff.tex 
LaTeX2e <2015/10/01> patch level 1
Babel <3.9m> and hyphenation patterns for 69 languages loaded.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.1  
     ■\ d o c u m e n t c l a s s { a r t i c l e }
```

Or if I compile with TexWorks GUI I get:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
entering extended mode
(C:/Users/garret/Desktop/TexExample/diff.tex
LaTeX2e <2015/10/01> patch level 1
Babel <3.9m> and hyphenation patterns for 69 languages loaded.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 �
     �\
```

But then if I copy and re-paste, or delete and CTRL+Z undo, and then compile, everything works as expected. So the black box or question-mark-inside-a-square character disappears. Some sort of ASCII/Unicode error?

**Comment by ftilmann** [comment] 2016-02-04 12:06
Thanks for the report. Unfortunately this is impossible for me to 'debug' as it seems quite specific to the specifics of the file and the editor as the copy/paste remedy demonstrates. I suspect the problem is with one of the input files.
Depending on how computer savvy you are you  could use a hex editor to look for hidden characters or simply see if the copy and re-paste trick applied to old.tex and new.tex and then latexdiff'ing also helps.  I will close this but feel free to reopen if you find latexdiff really introduces this.

**Closed by ftilmann** 2016-02-04 12:06 UTC

**Comment by sigma67** [comment] 2019-03-18 12:45
I just stumbled upon this issue as well (same setup, only TeXStudio instead of Texmaker). 

In case anyone else stumbles upon this: The solution for me was changing the encoding in TeXStudio to UTF-8 according to this [Stackoverflow post](https://tex.stackexchange.com/questions/154278/texstudio-changed-encoding).

**Comment by CecilR** [comment] 2020-12-09 02:50
> I just stumbled upon this issue as well (same setup, only TeXStudio instead of Texmaker).
> 
> In case anyone else with this problem finds this post: The solution for me was changing the encoding in TeXStudio to UTF-8 according to this [Stackoverflow post](https://tex.stackexchange.com/questions/154278/texstudio-changed-encoding).

This also solves the problem in my case.

**Comment by ftilmann** [comment] 2020-12-09 07:36
Thanks for this hint.  If you know what encoding is used, you should be able to use `--encoding` option

**Comment by amashigeo** [comment] 2025-01-17 12:57
I also met up with this problem. I use Texlive and the encoding is UTF-8. 
Finally I found that if I use powershell to run the latexdiff command, the invisible characters appear. But if I use cmd, it's all right.
