### ISSUE TITLE
\newcommand{\con} breaks latexdiff

### ISSUE THREAD

**Issue by bersbersbers** [ftilmann/latexdiff#70] opened 2016-11-30 17:19 UTC
Hi,
I have come across a very weird behavior on Windows, with a very simple MWE. This is how I can reproduce it on my machine:
```
echo \documentclass{article}\begin{document}\end{document} > a.tex
echo \documentclass{article}\newcommand{\con}{}\begin{document}\end{document} > b.tex
latexdiff a.tex b.tex
```

When I replace \con by \cont, everything works as expected. The issue does not reproduce on MacOS.

I feel this might be because CON is a reserved word on Windows (try "mkdir con", "echo something > con", or anything like that).  However, while AUX is another reserved word, replacing \con by \aux works fine...

This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.1903, Perl v5.24.0)
  (c) 2004-2016 F J Tilmann

I use ActivePerl (https://www.activestate.com/activeperl) 64 bit on Windows 10.

**Comment by ftilmann** [comment] 2016-11-30 17:43
I don't have access to Windows but cannot reproduce under Linux either (although you don't say what you get so I don't even know what I should expect to reproduce). However, I think it is quite unlikely that it should matter if a Windows reserved keyword is in the text file (also you are using Unix/Linux type shell commands, rather than DOS commands)
Have you inspected a.tex and b.tex . To me it seems far more plausible that something goes wrong in the echo command than anything being wrong with latexdiff

**Comment by bersbersbers** [comment] 2016-11-30 17:48
I have attached my tex files. Nothing going wrong there, it seems. (You may need quotation marks on Linux, I remember - not so on Windows.)

I expect latexdiff to terminate and output a compilable result; instead, latexdiff never terminates, runs until forces to terminate, and produces no output but "Terminating on signal SIGINT(2)".

[a.txt](https://github.com/ftilmann/latexdiff/files/622553/a.txt)
[b.txt](https://github.com/ftilmann/latexdiff/files/622554/b.txt)

**Comment by ftilmann** [comment] 2016-11-30 17:57
Thanks.  You can run with --verbose and --debug option to get a bit more of a clue where it fails (maybe). But unfortunately I will not be able to help you further on this (for reasons mentioned). You can hope this will be addressed from the community but don't hold your breath; so far I don't think any issue has been resolved by community input.  If it's important to you rather than just a curiosity I recommend reposting on Latex Stack Exchange; the question can reach a far larger audience there. I will leave your issue open for now, but if there is no further development will close it in a few weeks (if you do find a solution yourself or elsewhere, please come back here and post it)

**Comment by bersbersbers** [comment] 2016-11-30 18:19
I don't get anything useful out of --verbuse --debug:

```
C:\Users\xxx>more a.tex
\documentclass{article}\begin{document}\end{document}

C:\Users\xxx>more b.tex
\documentclass{article}\newcommand{\con}{}\begin{document}\end{document}

C:\Users\xxx>latexdiff --verbose --debug a.tex b.tex
This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.1903, Perl v5.24.0)
  (c) 2004-2016 F J Tilmann
Preamble Internal Type UNDERLINE
Preamble Internal Type SAFE
Preamble Internal Type FLOATSAFE
```

Anyway, the obvious solution is something like this on both input files (Windows batch file syntax):

`sed` "s-\\\con-\\\confoosion-g" old.tex > "%TEMP%\old.tex"

**Comment by bersbersbers** [comment] 2016-12-05 19:58
I do have some evidence now that the issue is indeed filesystem-related, Compare this snapshot:

![mycommand](https://cloud.githubusercontent.com/assets/12128514/20900074/eef5ab40-bafa-11e6-9ea7-a58403979781.PNG)

perl/latexdiff tries to create a file named "mycommand", which is the name of "\mycommand". Try the same with "\con", and it has to fail.

perl even tries to create some other invalid file names if I release the filter in procmon, but this fails silently and does not seem to cause issues:
![mycommand](https://cloud.githubusercontent.com/assets/12128514/20900149/327dab6a-bafb-11e6-9dca-e6fe1595ebcd.PNG)

**Comment by ftilmann** [comment] 2016-12-05 22:05
OK, I think I know where the problem lies, i.e. in subroutine  init_regex_arr_ext, where it tests whether the argument is a file (l. 2889 ff).  Apparently, for con this test for fileness ` ( -f $ arg )` hangs. I am still not sure why Windows perl tries to create these other files; for these the file test should come out negative. 
However, it is indeed a bug, which might trigger under Linux and Mac also in rare circumstances, so I intend to fix this eventually by adding an optional argument to init_regex_arr_ext that sets the nature of the other argument, but in the next few weeks I am probably too busy.

**Comment by bersbersbers** [comment] 2016-12-06 18:07
Yes, this is the problem! It actually hangs on `while (<FILE>)` without even entering the loop. Here's the confirmation:

perl code:
```
print "0";
init_regex_arr_ext("existing");
print "1";
init_regex_arr_ext("nonexisting");
print "2";
init_regex_arr_ext("con");
print "3";

sub init_regex_arr_ext {
	print "a";
	my ($arg)=@_;
	print "b";
	if ( -f $ arg ) {
		print "c";
		open(FILE,"$arg") or die ("Couldn't open $arg: $!");
		print "d";
		while (<FILE>) {
			print "e";
			chomp;
			print "f";
		}
		close(FILE);
	}
	print " ";
}
```

call:
```
C:\Users\xxx\Desktop>echo abc > existing

C:\Users\xxx\Desktop>rm nonexisting
rm: cannot remove `nonexisting': No such file or directory

C:\Users\xxx\Desktop>perl test.pl
```

output:
`0abcdef` 1ab 2abcd

Note the missing `3`.

**Comment by ftilmann** [comment] 2016-12-07 10:47
Thanks for running this test, which confirms my suspicion. I will let you know when I have fixed this and hopefully you are then able to quickly test on Windows.

**Comment by ftilmann** [comment] 2016-12-29 14:40
I have just made some changes: 035b8e7 , which should fix this issue. As I could never reproduce it in the first place I cannot verify. I will close the issue for now but if your tests show there is still a problem please reopen (and let me know)

**Closed by ftilmann** 2016-12-29 14:40 UTC
Labels: bug
