### ISSUE TITLE
Unescaped left brace in regex is deprecated, passed through in regex;

### ISSUE THREAD

**Issue by BEpresent** [ftilmann/latexdiff#61] opened 2016-10-10 11:04 UTC
As far as I know the deprecation warnings should be fixed in the most recent version. May be I did something wrong?

```

./latexdiff --version                                                                                                                                             
This is LATEXDIFF 1.2.1a  (Algorithm::Diff 1.1903, Perl v5.24.0)
  (c) 2004-2016 F J Tilmann

```
After performing `./latexdiff test2.tex test1.tex >  diff.tex `   the following error occurs: 

                                                                                                             
```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/command{ <-- HERE \\DIFaddbeginFL}{((?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}])*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*)}/ at ./latexdiff line 836.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/command{\\DIFaddbeginFL}{ <-- HERE ((?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}])*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*)}/ at ./latexdiff line 836.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin\{((?:picture|tikzpicture|DIFnomarkup)[\w\d*@]*)}(.*?)\\end{ <-- HERE \1}/ at ./latexdiff line 2161, <DATA> line 30487.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin\{((?:aligned|array|[pbvBV]?matrix|smallmatrix|cases|split))}(.*?)\\end{ <-- HERE \1}/ at ./latexdiff line 2166, <DATA> line 30487.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin\{((?:equation[*]?|displaymath|DOLLARDOLLAR)[*]?|(?:eqnarray|align|alignat|gather|multline|flalign)[*]?|SQUAREBRACKET)}(.*?)\\frac(([\s]*%[^\n]*?)*[\r\n|\r|\n])+\{(.*?)\\end{ <-- HERE \1}/ at ./latexdiff line 2051, <DATA> line 30487.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\begin\{((?:equation[*]?|displaymath|DOLLARDOLLAR)[*]?|(?:eqnarray|align|alignat|gather|multline|flalign)[*]?|SQUAREBRACKET)}(.*?)\\end{ <-- HERE \1}/ at ./latexdiff line 2170, <DATA> line 30487.
```

Working example:

text1.tex

```
%\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{article}

\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{revtex4-1}

%\documentclass[aps,pre,amsmath,amssymb,lengthcheck,showpacs,floatfix]{revtex4-1}
%\documentclass[superscriptaddress,twocolumn,pre,amsmath,showpacs,bibliography]{revtex4-1}
\usepackage{siunitx}
%\usepackage[]{inputenc}
\usepackage{graphicx}% Include figure files
\usepackage{dcolumn}% Align table columns on decimal point
\usepackage{bm}% bold math
\usepackage{colordvi}
\usepackage{epsfig}
%\usepackage{bm}
\usepackage{subcaption}
\usepackage{commath}
\usepackage[usenames]{color}
%\usepackage{natbib}
\usepackage{url}
 \usepackage[english]{babel}





\begin{document}

\title{Test 2016}

\author{xxxxxx}
%\affiliation{dadasdad}


\begin{abstract}
\noindent  Abstract:Test
\end{abstract}

\date{\today}
%\pacs{???}






\maketitle

\maketitle
%\onecolumngrid
\section{Introduction}




changed text

\section{Theory (WIP)}
%\bibliographystyle{unsrt}

%\bibliographystyle{abbrv}

\bibliographystyle{unsrtnat}

%\bibliography{ExportedItems}


\end{document}
```

test2.tex
```

%\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{article}

\documentclass[aps,pre,amsmath,amssymb,longbibliography,lengthcheck,showpacs,superscriptaddress,nofootinbib,floatfix]{revtex4-1}

%\documentclass[aps,pre,amsmath,amssymb,lengthcheck,showpacs,floatfix]{revtex4-1}
%\documentclass[superscriptaddress,twocolumn,pre,amsmath,showpacs,bibliography]{revtex4-1}
\usepackage{siunitx}
%\usepackage[]{inputenc}
\usepackage{graphicx}% Include figure files
\usepackage{dcolumn}% Align table columns on decimal point
\usepackage{bm}% bold math
\usepackage{colordvi}
\usepackage{epsfig}
%\usepackage{bm}
\usepackage{subcaption}
\usepackage{commath}
\usepackage[usenames]{color}
%\usepackage{natbib}
\usepackage{url}
 \usepackage[english]{babel}





\begin{document}

\title{Draft 2016}

\author{xxxxxx}
%\affiliation{dadasdad}


\begin{abstract}
\noindent  Abstract: Test
\end{abstract}

\date{\today}
%\pacs{???}






\maketitle

\maketitle
%\onecolumngrid
\section{Introduction}




asdad aLorem ipsum dolor sit amet, conseteted diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\section{Theory (WIP)}
%\bibliographystyle{unsrt}

%\bibliographystyle{abbrv}

\bibliographystyle{unsrtnat}

\bibliography{ExportedItems}


\end{document}
```

**Comment by ftilmann** [comment] 2016-10-10 23:03
Exemplary error report. I hope I have this fixed with cfe445c..a83d9cb 
(still on perl 18 so cannot reproduce the errors myself).

**Comment by BEpresent** [comment] 2016-10-18 11:27
Excuse the late response. Some left braces were fixed, some remain (rest is same as above): (Should I open a new issue?)

```

./latexdiff --version                                                                                                                                             
This is LATEXDIFF 1.2.1a  (Algorithm::Diff 1.1903, Perl v5.24.0)
  (c) 2004-2016 F J Tilmann

$ ./latexdiff test2.tex test1.tex > diff.tex                                                                                                                        (master✱) 
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/command\{\\DIFaddbeginFL}{ <-- HERE ((?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}])*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*)}/ at ./latexdiff line 837.

```

**Comment by ftilmann** [comment] 2016-10-22 07:14
I added the escape to the left brace in l 837 mentioned before in your last comment (commit 51777a0 ). Let me know if there are any more.

**Comment by BEpresent** [comment] 2016-10-22 18:07
No errors anymore, thanks.

**Comment by ftilmann** [comment] 2016-10-23 12:52
Thanks for testing. I will close this then.

**Closed by ftilmann** 2016-10-23 12:52 UTC
