### ISSUE TITLE
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2196.

### ISSUE THREAD

**Issue by devillemereuil** [ftilmann/latexdiff#128] opened 2017-12-03 21:17 UTC
When trying to use latexdiff on a specific file, I'm hitting a bug in latexdiff (the error message seems to be signing a syntax error in the perl script):
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2196.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=123 at /usr/bin/latexdiff line 2196.

This only happens for a particular file that worked before, but not anymore (don't know what changed though as this also happening on my openSUSE Leap system which is stable in terms of packaging...).

Since the error seem to be of syntax origin, I thought reporting this would help (maybe not, it seems I can't create a MWE from the problematic files...).

**Comment by ftilmann** [comment] 2017-12-04 06:13
Without an MWE it might be difficult, but could you specify the exact version of latexdiff and post a copy of lines 2194-2198 in your version of latexdiff, so that I can be sure which line is causing the problem.

**Comment by devillemereuil** [comment] 2017-12-04 07:31
I've tested latexdiff 1.1.1 (on openSUSE Leap 42.2) and 1.2.0 (on openSUSE Tumbleweed). Both yield the same result.

Below is the snippet of code from version 1.2.0:

      while( m/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)\}(.*?)\\frac\{(.*?)\\end\{\1\}/s ) {
        ### if there isn't any more //frac before the first //end in the pattern $2 then there should be an \\end{...} in $2
        if( $2 !~ m/\\end\{$1\}/s ) {
          ### from now on CURRFRAC is the frac we are looking at
          s/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)\}(.*?)\\frac\{(.*?)\\end\{\1\}/\\begin\{$1\}$2CURRFRAC\{$3\\end\{$1\}/s;
          while( m/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)\}(.*?)CURRFRAC\{(.*?)\\end\{\1\}/s ) {
             if( m/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)\}(.*?)CURRFRAC\{($pat_n)\}([\s]*(%[^\n]*?)*[\r\n|\r|\n])+[\s]*\{(.*?)\\end\{\1}/s ) {
                   s/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)\}(.*?)CURRFRAC\{($pat_n)\}([\s]*(%[^\n]*?)*[\r\n|\r|\n])+[\s]*\{(.*?)\\end\{\1\}/\\beg$
               }
              else { # there is no comment or \n between the two brackets {}{}
              ### change CURRFRAC to FRACSTART so we can change them all back to //frac{ when we finish
                   s/\\begin\{($MATHENV|$MATHARRENV|SQUAREBRACKET)}(.*?)CURRFRAC\{(.*?)\\end\{\1}/\\begin{$1}$2FRACSTART\{$3\\end{$1}/s;
              }
            }
        }

Sorry, it's very hard to come up with a MWE, as this is a whole scientific article... I have older versions that seem to work, but finding what differences are triggering in the ocean of modification is tedious...

**Comment by devillemereuil** [comment] 2017-12-04 07:36
To be sure: the line triggering the bug is:

    if( $2 !~ m/\\end\{$1\}/s ) {

**Comment by ftilmann** [comment] 2017-12-04 17:23
Thanks. This is is in a part of the code which was contributed, and which I need to get my head around but in any case from staring at this, I do not see how this error condition could be triggered.

I cannot go on without an example triggering the error message. I appreciate there might be issues of privacy with a manuscript draft, but would you consider sending me the long failing example through private email (my email address is in the man pages of latexdiff under 'BUGS') or otherwise. I would commit to keeping it confidential.

**Comment by devillemereuil** [comment] 2017-12-06 02:58
I can't seem to send an email to your berliOS email address ("host not found"), is it the right one ?

**Comment by ftilmann** [comment] 2017-12-06 06:06
No, Berlios is long defunct, not sure where you found this one. You can use tilmann -at- gfz-potsdam.de , which is also listed in any of the current (last few years) man pages under BUGS

**Comment by devillemereuil** [comment] 2017-12-09 03:51
FYI, commenting out the if statement above (with everything coming between the brackets {} after) and leaving only the part in "else" resutls in a working code.

**Comment by ftilmann** [comment] 2017-12-29 14:44
Hi, I finally go around to test the file you sent by email. Unfortunately, I cannot reproduce this error with either the current (github) version of latexdiff or v1.1.1 (both tested on perl 5.18.2 and 5.22.1 - for the latter and v1.1.1 I get many depracation warnings but this is a known issue and has already been fixed in newer versions).
So I am stuck. I am sorry but I will close this issue for now, as I don't really see a way of moving ahead - and even for you it seems specific to one file.

**Comment by JVAQUEROM** [comment] 2018-01-22 19:33
Hello, I am also using openSuSE Leap 42.3 and I have a similar issue:

`Use of uninitialized value $2 in pattern match (m//) at /usr/local/bin/latexdiff line 2550, <DATA> line 77075.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=58 at /usr/local/bin/latexdiff line 2550, <DATA> line 77075.`

As devillemereuil, my document is a scientific article, and difficult to give a minimal example, but I will try to do it.

I hope this gives some light on the matter!

**Comment by ftilmann** [comment] 2018-01-23 07:50
Thanks for your report, which confirms it is an issue affecting several people. However, with devillemereuil  I could not reproduce the error even when he sent me the full example (as you see in the trail). The error message is coming from perl not from latexdiff.   An MWE would still be very useful I think but also information on which version of perl you are using.

**Comment by JVAQUEROM** [comment] 2018-01-23 09:36
Running `perl --version`I get:
`This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-thread-multi`

```
latexdiff --version
This is LATEXDIFF 1.2.1  (Algorithm::Diff 1.15 fast, Perl v5.18.2)                                                                                                                                                                                                            
  (c) 2004-2017 F J Tilmann
```

I'll try to get a MWE, maybe in the weekend I can work on it.

Thank you!!

**Comment by patta42** [comment] 2018-04-13 09:35
I am having a similar problem, and the line where it fails is line 2446 of latexdiff.
I use opensuse 42.3

perl v5.18.2
latexdiff 1.2.1  (Algorithm::Diff 1.15 so, Perl v5.18.2)

I could create a file that seems to be a minimal example, but it is quite strange:

```
\documentclass{article}
\begin{document}
  \begin{equation}
  \end{equation}
  \begin{equation}
    \frac{}
  \end{equation}
 ü
\end{document}
```
The file is saved with utf-8 encoding.

Then:

```
> latexdiff test-ld.tex test-ld.tex 
Use of uninitialized value $2 in pattern match (m//) at /usr/local/texlive/2017/bin/x86_64-linux/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=3 at /usr/local/texlive/2017/bin/x86_64-linux/latexdiff line 2446.
```

I have noticed the following:
- If I delete the first equation environment, it works. 
- If I delete the `\frac` or the corresponding `{}`, it works. I can delete the closing `}` and it still fails.
- If I delete the `ü`, it works.

From the comments in latexdiff, I think that the two `equation` environments and the `\frac{}` are required to reach this particular line of latexdiff. The `ü` seems to be required, too, since the error `panic: sv_pos_b2u: bad byte offset` seems to be related to utf-8. However, if one googles it, the bug reports are related to perl 5.8, not perl 5.18.


HTH,

Patrick

**Comment by JVAQUEROM** [comment] 2018-04-13 09:44
I confirm this throws  the error for me too. But I have other line, as previously reported

```
Use of uninitialized value $2 in pattern match (m//) at /usr/local/bin/latexdiff line 2550.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=3 at /usr/local/bin/latexdiff line 2550.
```

Thank you @patta42 for the WME, it was very difficult to me to simplify my .tex file...the error seemed to come and go and drove me crazy.

**Comment by ftilmann** [comment] 2018-04-13 09:50
@patta42 , thanks for constructing the MWE. Unfortunately I still cannot reproduce. It works fine for me both for v1.2.1 and the github development version. For 1.2.0 I get the warnings reported by @JVAQUEROM  . The only obvious difference is that I use Perl v5.22.1  - I have upgraded all my computers now, so cannot easily test anymore on v5.18.  So at this stage I can only advise to upgrade your perl - sorry to not be more helpful. Another possibility is that copy/pasting the file from this page is not enough to reproduce it completely.  If you have the possibility to make the MWE available as a 'binary' through dropbox or ftp site, then I could test this also.

**Comment by devillemereuil** [comment] 2018-04-13 09:58
Sorry, can't reproduce with this MWE either using openSUSE Leap 15.0 and Tumbleweed (both use Perl 5.26 and latexdiff 1.2.0)... Though my original file is still triggering the bug in these settings. This bug is super weird!

**Comment by patta42** [comment] 2018-04-13 10:12
Here is a "binary" version of the file, although I don't think it makes a difference. 

It is a bit hard to update perl without updating my entire OS. There is a dependency on perl 5.18 by the package manager which I do not want to break.

[test-ld.zip](https://github.com/ftilmann/latexdiff/files/1906873/test-ld.zip)

**Comment by patta42** [comment] 2018-04-13 12:50
It obviously is a perl issue. I have installed ActivePerl 5.26.1, and with this it runs without problems:

```
/opt/ActivePerl-5.26/bin/perl5.26.1 `which latexdiff` test-ld.tex test-ld.tex
\documentclass{article}
%DIF LATEXDIFF DIFFERENCE FILE
%DIF DEL test-ld.tex   Fri Apr 13 11:16:38 2018
%DIF ADD test-ld.tex   Fri Apr 13 11:16:38 2018
%DIF PREAMBLE EXTENSION ADDED BY LATEXDIFF
%DIF UNDERLINE PREAMBLE %DIF PREAMBLE
\RequirePackage[normalem]{ulem} %DIF PREAMBLE
\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE
\providecommand{\DIFadd}[1]{{\protect\color{blue}\uwave{#1}}} %DIF PREAMBLE
\providecommand{\DIFdel}[1]{{\protect\color{red}\sout{#1}}}                      %DIF PREAMBLE
%DIF SAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddbegin}{} %DIF PREAMBLE
\providecommand{\DIFaddend}{} %DIF PREAMBLE
\providecommand{\DIFdelbegin}{} %DIF PREAMBLE
\providecommand{\DIFdelend}{} %DIF PREAMBLE
%DIF FLOATSAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}} %DIF PREAMBLE
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}} %DIF PREAMBLE
\providecommand{\DIFaddbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFaddendFL}{} %DIF PREAMBLE
\providecommand{\DIFdelbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFdelendFL}{} %DIF PREAMBLE
%DIF END PREAMBLE EXTENSION ADDED BY LATEXDIFF

\begin{document}
  \begin{equation}
  \end{equation}
  \begin{equation}
    \frac{}
  \end{equation}
 ü
\end{document}
```

**Comment by JVAQUEROM** [comment] 2018-07-19 12:02
I updated to opensuse 15 and still affected by the bug. Output is:

```
This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.15 so, Perl v5.26.1)                                                                                                                                                                                                              
  (c) 2004-2016 F J Tilmann                                                                                                                                                                                                                                                   
Preamble Internal Type UNDERLINE                                                                                                                                                                                                                                              
Preamble Internal Type SAFE                                                                                                                                                                                                                                                   
Preamble Internal Type FLOATSAFE                                                                                                                                                                                                                                              
Negative repeat count does nothing at /usr/bin/latexdiff line 1064, <DATA> line 26542.                                                                                                                                                                                        
hyperref package detected.                                                                                                                                                                                                                                                    
Preamble Internal Type HYPERREF                                                                                                                                                                                                                                               
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/command{ <-- HERE \\DIFaddbeginFL}{((?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}])*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*\})*)}/ at /usr/bin/latexdiff line 1171, <DATA> line 31168.  
```
The MWE provided by @patta42 works well, however..this is super weird...

**Comment by eggsperde** [comment] 2019-04-28 16:27
Google led me here and I just wanted to confirm the issue. I am (still) on opensuse 41.3 and wanted to compare my thesis with a previous version. A few lines of Python iterate through the directory and compare individual files. This is what I get (apologies for the non-appropriately formatted code): 

`Couldn't open /home/eggs/thesis/final/content/chapter-microsimulation_classification_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=386 at /usr/bin/latexdiff line 2446.

WARNING: Inconsistency in length of input string and parsed string:
     This often indicates faulty or non-standard latex code.
     In many cases you can ignore this and the following warning messages.
 Note that character numbers in the following are counted beginning after \begin{document} and are only approximate.
LEFTBRACE 20mm\CRIGHTBRACE  % %\CLEFTBRACE \usekomafont\CLEFTBRACE chapte
                              ^^^^^^^^^^^^^                              
Missing characters near word 653 character index: 4560-4573 Length: 12 Match: |\CLEFTBRACE | (expected match marked above).

WARNING: Inconsistency in length of input string and parsed string:
     This often indicates faulty or non-standard latex code.
     In many cases you can ignore this and the following warning messages.
 Note that character numbers in the following are counted beginning after \begin{document} and are only approximate.
%\CLEFTBRACE 
                              ^^^^^^^^^^^^^                              
Missing characters near word 0 character index: 0-13 Length: 12 Match: |\CLEFTBRACE | (expected match marked above).
Couldn't open /home/eggs/thesis/final/content/chapter-TA_lattice_model_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=231 at /usr/bin/latexdiff line 2446.
Couldn't open /home/eggs/thesis/final/content/chapter-ITS_lattice_models_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Couldn't open /home/eggs/thesis/final/content/chapter-FSM_TA_model_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=148 at /usr/bin/latexdiff line 2446.
Couldn't open /home/eggs/thesis/final/content/chapter-lattice_model_survey_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Couldn't open /home/eggs/thesis/final/content/chapter-discretisation_errors_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Couldn't open /home/eggs/thesis/final/content/chapter-driver_differences_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Couldn't open /home/eggs/thesis/final//media/datenhalde/UniShare/Diss/Presentations/Research/interdriver_differences_table.tex: No such file or directory at /usr/bin/latexdiff line 1562.
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=271 at /usr/bin/latexdiff line 2446.
Use of uninitialized value $2 in pattern match (m//) at /usr/bin/latexdiff line 2446.
panic: sv_pos_b2u: bad byte offset, blen=0, byte=206 at /usr/bin/latexdiff line `2446.`

**Comment by ftilmann** [comment] 2019-04-29 12:05
@eggsperde   It is hard to tell but this might or might not the same bug. 
Your very first error message points to a failure to find a file. 
```
Couldn't open /home/eggs/thesis/final/content/chapter-microsimulation_classification_text.tex: No such file or directory at /usr/bin/latexdiff line 1562.
```
(do you use --flatten option, and that file is missing?)
If you are able to produce a short MWE that leads to error, it would be possible to look at them. Without that it is not really possible to start. 

Also use `latexdiff --version` to report both latexdiff and perl version numbers.  There are some indications in the thread that this is essentially a bug (or at least incompatibility) in perl, which is fixed in latest version.

**Comment by eggsperde** [comment] 2019-04-30 20:43
You are right about the very first error message and it got me quite confused, because I quadruple checked and the file was there. The main file also compiles without errors from within TeXstudio and it loads the linked chapter as expected.

`latexdiff --version` outputs `This is LATEXDIFF 1.2.1  (Algorithm::Diff 1.15 so, Perl v5.18.2)`.

I just wanted to report that I found the issue, too because it seems strange that so many opensuse users are affected. Apologies for not coming up with an MWE...  I spent two hours already manually marking changes and do not want to deal with this thesis anymore.

**Comment by ftilmann** [comment] 2020-09-12 19:41
As I never managed to nail where the problem is, and the subroutine referred to in the beginning of the thread has been rewritten, it is quite possible this issue has gone away. I will close this issue

**Closed by ftilmann** 2020-09-12 19:41 UTC

**Comment by devillemereuil** [comment] 2020-09-13 08:36
This hasn't been a problem for me on Tumbleweed for a while now, FYI. As far as I'm concerned, closing this issue is sensible!

**Comment by JVAQUEROM** [comment] 2020-09-15 06:44
I am currently on openSuSE 15.2 and haven't met the error again, but if it does, I'll report back again. Thank you!!
