### ISSUE TITLE
Handling subfiles

### ISSUE THREAD

**Issue by KueWW** [ftilmann/latexdiff#177] opened 2019-09-16 13:48 UTC
Hi there,

I want to diff a huge LaTeX document with subfiles.
The document uses the LaTeX switches

- notinsubfile
- onlyinsubfile

In _--flatten_ mode latexdiff doesn't work for sure. The one "diff.tex" can't be compiled because
all the content of the switches is included.
In _non --flatten_ mode it doesn't show diffrerences. It sems that the subfiles are not included.
How can I handle this?

Thanks in advance

**Comment by ftilmann** [comment] 2019-09-17 06:33
I am not really familar with the subfiles packages so don't know how the switches operate.
I guess you mean that --flatten ignores the switches. 
In the short run you would need to write a script that diff's the individual included files.  By diverting the output to its own 'diff' directory you could then probably just use the same master file, or if you use -diff.tex extensions, then you must prepare a special version of the masterfile including the diff'ed variants
In the long run you can put in a feature request to extend latexdiff --flatten to properly understand these switches (or if you know a bit of perl implement this yourself).  In either case it would be helpful to supply a minimal test case demonstrating the operation of these switches.  If you rely on me be warned that it might take a long (or even indefinite) time until I get around to address it as I get little time to maintain latexdiff these days.  But occasionally I do implement feature requests, and there is always the chance that somebody else picks this up.

**Comment by KueWW** [comment] 2019-09-17 07:14
Thanks for your quick reply.

In the first step I will try the script way.
In the second step I'll try to extend _--flatten_.
When I start this I'll keep you updated.

**Comment by KueWW** [comment] 2019-09-17 08:15
Hi,

I'm sorry to reopen the issue.
I've read the help of _latexdiff_ again.

Is it possible to ignore the switches by using _exclude-textcmd_, _exclude-safecmd_ or something similar?
I think I do not understand how these options are working.....

**Comment by ftilmann** [comment] 2019-09-17 10:57
These options work on commands. They are unaware of options. So I don't think they would work.  If you show me  a short example, I might be able to say more, as I am not sure how these options are used.

**Comment by KueWW** [comment] 2019-09-18 07:57
I'll try to give you an short example soon. Hopefully at the end of the week.....

**Comment by KueWW** [comment] 2019-09-23 10:11
Hi there,

I've set up a short example.
I am confused now because this short example works!
The huge one don't. There's no idea how to get that working.......
I'll try to get this example causing the error......

[version-old.zip](https://github.com/ftilmann/latexdiff/files/3641625/version-old.zip)
[version-new.zip](https://github.com/ftilmann/latexdiff/files/3641628/version-new.zip)

**Comment by ftilmann** [comment] 2020-09-12 19:43
Closing because no way to reproduce error. You can reopen if there is an MWE illustrating the problem and failing

**Closed by ftilmann** 2020-09-12 19:43 UTC
