### ISSUE TITLE
Don't use `die` when exiting successfully

### ISSUE THREAD

**Issue by lorenzleutgeb** [ftilmann/latexdiff#253] opened 2022-01-28 09:23 UTC
I was very surprised to get non-zero exit codes for these invocations:

```console
> latexdiff-vc --version ; echo $?
This is LATEXDIFF-VC 1.3.1.1
  (c) 2005-2020 F J Tilmann
255
> latexdiff --version ; echo $?
This is LATEXDIFF 1.3.1.1 (Algorithm::Diff 1.15 so, Perl v5.34.0)
  (c) 2004-2020 F J Tilmann
255
```

It turns out that you use [`die`](https://perldoc.perl.org/functions/die) to print the version string and exit:

https://github.com/ftilmann/latexdiff/blob/af22466ac358e69c3d932a986c1c9ed971b99585/latexdiff-vc#L150

However, `die` sets a non-zero exit code, indicating an error. When printing the version string is everything that the program should do, then I'd also expect it to exit with an exit code of zero once that's done.

The documentation for `die` states:

> If you need to exit the process with a specific exit code, see `exit`.

IMO, [`print`](https://perldoc.perl.org/functions/print) followed by [`exit`](https://perldoc.perl.org/functions/exit) should be used, like here:

https://github.com/ftilmann/latexdiff/blob/af22466ac358e69c3d932a986c1c9ed971b99585/latexdiff#L490-L491

**Comment by ftilmann** [comment] 2022-01-28 09:55
Thanks for reporting. This seems a duplicate of #248  and should be fixed on master (and actually in the very latest release, which was made just after). I will close. Let me know if there is still a problem.

**Closed by ftilmann** 2022-01-28 09:55 UTC

**Comment by lorenzleutgeb** [comment] 2022-01-28 10:11
Yes, sorry for duplicating, and thanks for fixing.
